apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /
    #    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Catch all server names
    nginx.ingress.kubernetes.io/server-snippet: "server_name ~^.*$;"
    #    nginx.ingress.kubernetes.io/configuration-snippet: |
    #      more_set_headers "X-Frame-Options: SAMEORIGIN";
    #      more_set_headers "Content-Security-Policy: frame-ancestors 'none'";
  name: refractr-prod
  namespace: refractr-prod
spec:
  tls:
  - hosts:
    - refractr.allizom.org
    secretName: refractr-allizom-org-tls
  rules:
  - host: refractr.allizom.org
    http:
      paths:
      - path: /
        backend:
          serviceName: refractr
          servicePort: 50023
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-refractr-prod
  namespace: refractr-prod
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    k8s-app: ingress-nginx
