---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: refractr
  namespace: refractr-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: refractr-web
      containers:
      - image: itsre/refractr:786a3e0b9a6a061dbf7eed1b089b25ca22f6ade4
        name: refractr-web
