---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: refractr
  namespace: refractr-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: refractr-web
      containers:
      - image: itsre/refractr:0038d690fc12665e228f0412c350ce43e7bb7d43
        name: refractr-web
