---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: refractr
  namespace: refractr-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: refractr-web
      containers:
      - image: itsre/refractr:v0.0.1-5-g4211653
        name: refractr-web
