apiVersion: v1
kind: Service
metadata:
  name: refractr
  namespace: refractr-stage
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 30592
    protocol: TCP
    targetPort: 80
  selector:
    app: refractr
  type: NodePort
